# Generated by Django 3.0.4 on 2020-03-05 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='created_at',
            new_name='date',
        ),
    ]
