# Generated by Django 3.0.4 on 2020-03-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_auto_20200305_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='date',
            new_name='created_at',
        ),
    ]
