# Generated by Django 3.0.4 on 2020-03-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_auto_20200305_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
