# Generated by Django 3.0.4 on 2020-03-05 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0004_habit_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='habit',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='habit',
            name='unit',
            field=models.CharField(default='steps', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='habit',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit_tracker.HabitRecord'),
        ),
    ]
