# Generated by Django 3.0.4 on 2020-03-06 18:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habit_tracker', '0005_auto_20200305_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='due_date',
            field=models.DateField(default=datetime.date(2020, 3, 6)),
        ),
        migrations.AddField(
            model_name='habit',
            name='observer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habit',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitrecord',
            name='due_date',
            field=models.DateField(default=datetime.date(2020, 3, 6)),
        ),
        migrations.AlterField(
            model_name='habit',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit_record', to='habit_tracker.HabitRecord'),
        ),
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('due_date', 'record')},
        ),
    ]
