# Generated by Django 3.0.4 on 2020-03-06 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0008_auto_20200306_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='record',
        ),
        migrations.AddField(
            model_name='habitrecord',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit_records', to='habit_tracker.Habit'),
        ),
        migrations.AlterUniqueTogether(
            name='habitrecord',
            unique_together={('due_date', 'habit')},
        ),
        migrations.RemoveField(
            model_name='habitrecord',
            name='related_habit',
        ),
    ]
