# Generated by Django 3.0.4 on 2020-03-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0009_auto_20200306_2125'),
        ('habit_tracker', '0010_auto_20200306_1952'),
    ]

    operations = [
    ]
