# Generated by Django 3.0.4 on 2020-03-08 20:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habit_tracker', '0011_merge_20200307_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='due_date',
            field=models.DateField(default=datetime.date(2020, 3, 8)),
        ),
        migrations.AlterField(
            model_name='habit',
            name='observer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observed_habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habitrecord',
            name='due_date',
            field=models.DateField(default=datetime.date(2020, 3, 8)),
        ),
    ]
