# Generated by Django 3.0.4 on 2020-03-08 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0011_merge_20200307_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='due_date',
            field=models.DateField(default=datetime.date(2020, 3, 8)),
        ),
        migrations.AlterField(
            model_name='habitrecord',
            name='due_date',
            field=models.DateField(default=datetime.date(2020, 3, 8)),
        ),
    ]
